<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="Login de COVID-19 Info">
<meta name="keywords" content="COVID, COVID-19, Coronavirus, Girardot, COVID Colombia, Colombia, Pandemia Colombia, COVID Info Colombia">
<link rel="shortcut icon" href="../assets/img/logo.png" type="image/x-icon">
<meta name="author" content="Tecnico en Sistemas: Daniel Romero Gómez">
<!-- CSS -->
<link rel='stylesheet' href='css/familySans.css'>
<link rel='stylesheet' href='css/familyOleo.css'>
<link rel="stylesheet" href="css/2.css">
<link rel="stylesheet" href="css/style.css">
<!--Termina CSS-->
<!--Inicia librerias SummerNote-->
<link href="https://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote-bs4.css" rel="stylesheet">
<script src="js/jquerysummer.js"></script>
<script src="js/poppersummer.js"></script>
<script src="js/bootstrapsummer.js"></script>
<script src="js/jqueryslimsummer.js"></script>
<script src="js/summer.js"></script>
<!--Termina librerias SummerNote-->
